---
title: "World Record Mine"
author: "Nick Reeves"
date: "March 9, 2020"
output: html_document
---

```{r, Reading in Packages}
library(rvest)
library(tidyverse)
library(stringr)
library(lubridate)
```

```{r, Time-formatting}
#Creating a function to take in a time and turn it into a numeric vector with seconds as the units. 

time_fun <- function(x){ 
  times <- x
  times_split <- str_split(x,":")
  
  for(i in 1:length(times)){
    times[i] <- ifelse(str_detect(times[i], ":"),
                       as.numeric(60*as.numeric(times_split[[i]][1]) + as.numeric(times_split[[i]][2]) ),
                       as.numeric(times[i]))
    }
  return(as.numeric(times))
  }
```

```{r, Name-formatting}
#Creating a function to clean the format of some names. 

name_fun <- function(x){
  names <- x
  for (i in 1:length(names)){
    names[i] <- str_c(str_split(names[i], " ")[[1]][3], str_c(" ", str_split(names[i], " ")[[1]][4]))
  }
  return(names)
}
```

```{r, 50 Free}

#Reading in URL for 50 free. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable.  

url_50free <- "https://en.wikipedia.org/wiki/World_record_progression_50_metres_freestyle"

page_50free <- read_html(url_50free)

tables_50free <- html_nodes(page_50free, "table")

men_50free_lc <- html_table(tables_50free[[1]]) %>% 
  select(Time, Swimmer = Name, Date, Nationality, Location) %>%
  mutate(Distance = "50", Stroke = "Free", Format = "lc", Sex = "M")
men_50free_lc$Date<-  as.Date(men_50free_lc$Date, format = "%b %d, %Y")
men_50free_lc$Time <- time_fun(men_50free_lc$Time)


men_50free_sc <- html_table(tables_50free[[2]]) %>% 
  select(Time, Swimmer = Name, Date, Nationality, Location) %>%
  mutate(Distance = "50", Stroke = "Free", Format = "sc", Sex = "M")
men_50free_sc$Date<-  as.Date(men_50free_sc$Date, format = "%d %B %Y")
men_50free_sc$Time <- time_fun(men_50free_sc$Time)

women_50free_lc <- html_table(tables_50free[[3]]) %>% 
  select(Time, Swimmer = Name, Date, Nationality, Location) %>%
  mutate(Distance = "50", Stroke = "Free", Format = "lc", Sex = "W") 
women_50free_lc$Date<-  as.Date(parse_date_time(women_50free_lc$Date, c("%b %d, %Y", "%d %b %Y")))
women_50free_lc$Time <- time_fun(women_50free_lc$Time)

women_50free_sc <- html_table(tables_50free[[4]]) %>% 
  select(Time, Swimmer = Name, Date, Nationality, Location) %>%
  mutate(Distance = "50", Stroke = "Free", Format = "sc", Sex = "W")
women_50free_sc$Date<-  as.Date(women_50free_sc$Date, format = "%d %B %Y")
women_50free_sc$Time <- time_fun(women_50free_sc$Time)

free50 <- bind_rows(men_50free_lc,men_50free_sc, women_50free_lc, women_50free_sc) #Binding data into cumulative dataframe. 

```

```{r, 100 Free}

#Reading in URL for 100 free. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 

url_100free <- "https://en.wikipedia.org/wiki/World_record_progression_100_metres_freestyle"

page_100free <- read_html(url_100free)

tables_100free <- html_nodes(page_100free, "table")

men_100free_lc <- html_table(tables_100free[[1]]) %>% 
  select(Time, Swimmer = Name, Date, Nationality, Location) %>%
  mutate(Distance = "100", Stroke = "Free", Format = "lc", Sex = "M")
men_100free_lc$Date <- as.Date(men_100free_lc$Date, format = "%d %b %Y")
men_100free_lc$Time <- time_fun(men_100free_lc$Time)

men_100free_sc <- html_table(tables_100free[[2]]) %>% 
  select(Time, Swimmer =Name, Date, Nationality, Location) %>%
  mutate(Distance = "100", Stroke = "Free", Format = "sc", Sex = "M")
men_100free_sc$Date <- as.Date(men_100free_sc$Date, format = "%d %b %Y")
men_100free_sc$Time <- time_fun(men_100free_sc$Time)

women_100free_lc <- html_table(tables_100free[[3]]) %>% 
  select(Time, Swimmer = Name, Date, Nationality, Location) %>%
  mutate(Distance = "100", Stroke = "Free", Format = "lc", Sex = "W")
women_100free_lc$Date <- as.Date(women_100free_lc$Date, format = "%d %b %Y")
women_100free_lc$Time <- time_fun(women_100free_lc$Time)

women_100free_sc <- html_table(tables_100free[[4]]) %>% 
  select(Time, Swimmer = Name, Date, Nationality, Location) %>%
  mutate(Distance = "100", Stroke = "Free", Format = "sc", Sex = "W")
women_100free_sc$Date <- as.Date(women_100free_sc$Date, format = "%d %b %Y")
women_100free_sc$Time <- time_fun(women_100free_sc$Time)



free100 <- bind_rows(men_100free_lc,men_100free_sc,women_100free_lc,women_100free_sc)
```

```{r, 200 Free}

#Reading in URL for 200 free. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 

url_200free <- "https://en.wikipedia.org/wiki/World_record_progression_200_metres_freestyle"

page_200free <- read_html(url_200free)

tables_200free <- html_nodes(page_200free, "table")

men_200free_lc <- html_table(tables_200free[[1]]) %>% 
  select(Time,Swimmer,Date,Location = Place) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "200", Stroke = "Free", Format = "lc", Sex = "M")
men_200free_lc$Swimmer <- name_fun(men_200free_lc$Swimmer)
men_200free_lc$Date <- as.Date(men_200free_lc$Date, format = "%B %d, %Y")
men_200free_lc$Time <- time_fun(men_200free_lc$Time)

men_200free_sc <- html_table(tables_200free[[2]]) %>% 
  select(Time,Swimmer,Date,Location = Place) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "200", Stroke = "Free", Format = "sc", Sex = "M")
men_200free_sc$Swimmer <- name_fun(men_200free_sc$Swimmer)
men_200free_sc$Date <- as.Date(men_200free_sc$Date, format = "%B %d, %Y")
men_200free_sc$Time <- time_fun(men_200free_sc$Time)

women_200free_lc <- html_table(tables_200free[[3]]) %>% 
  select(Time,Swimmer,Date,Location = Place) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "200", Stroke = "Free", Format = "lc", Sex = "W")
women_200free_lc$Swimmer <- name_fun(women_200free_lc$Swimmer)
women_200free_lc$Date <- as.Date(women_200free_lc$Date, format = "%B %d, %Y")
women_200free_lc$Time <- time_fun(women_200free_lc$Time)

women_200free_sc <- html_table(tables_200free[[4]]) %>% 
  select(Time,Swimmer,Date,Location = Place) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "200", Stroke = "Free", Format = "sc", Sex = "W")
women_200free_sc$Swimmer <- name_fun(women_200free_sc$Swimmer)
women_200free_sc$Date <- as.Date(women_200free_sc$Date, format = "%B %d, %Y")
women_200free_sc$Time <- time_fun(women_200free_sc$Time)
```

```{r, 200 Free Nationality Adjustments}

#Manually entering nationality given that the entries were represented by a flag in the original dataset. 

men_200free_lc$Nationality <- c("Australia", "Hungary", "Austria", "Australia", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "France", "Australia", "United States", "Great Britain", "United States", "Australia", "Australia", "Japan", "Australia"," Japan","Japan","Japan","Japan", "United States", "Australia", "United States", "United States", "United States", "Germany", "United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States", "Soviet Union", "United States","United States", "West Germany", "West Germany", "West Germany", "West Germany", "Australia", "Italy", "Australia", "Australia", "Australia", "Australia", "Australia", "Netherlands", "Netherlands", "Australia", "Australia", "United States", "United States" , "Germany")

men_200free_sc$Nationality <- c("Germany","Germany", "Italy", "Australia", "Australia", "Australia", "Germany", "Germany")

women_200free_lc$Nationality <- c("Australia", "United States", "United States", "United States", "United States", "Netherlands", "Netherlands", "Netherlands",  "Netherlands", "Denmark", "Australia", "Australia", "Australia", "Australia", "Australia", "Australia", "United States", "United States", "United States", "United States", "United States", "United States", "Australia", "Australia", "United States", "Australia", "East Germany", "United States", "United States", "East Germany", "East Germany", "East Germany", "East Germany", "United States", "United States", "United States", "East Germany", "East Germany", "Germany", "Germany", "Italy", "France", "Italy", "Italy", "Italy", "Italy", "Italy")

women_200free_sc$Nationality <- c("Germany", "Costa Rica", "Costa Rica", "United States", "Australia", "France", "Italy", "Italy", "Sweden", "Sweden")

free200 <- bind_rows(men_200free_lc,men_200free_sc,women_200free_lc,women_200free_sc)
```


```{r, 400 Free}

#Reading in URL for 400 free. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 

url_400free <- "https://en.wikipedia.org/wiki/World_record_progression_400_metres_freestyle"

page_400free <- read_html(url_400free)

tables_400free <- html_nodes(page_400free, "table")

men_400free_lc <- html_table(tables_400free[[1]]) %>% 
  select(Time,Swimmer,Date,Location) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "400", Stroke = "Free", Format = "lc", Sex = "M")
men_400free_lc$Swimmer <- name_fun(men_400free_lc$Swimmer)
men_400free_lc$Date <- as.Date(men_400free_lc$Date, format = "%d %b %Y")
men_400free_lc$Time <- time_fun(men_400free_lc$Time)

men_400free_sc <- html_table(tables_400free[[2]]) %>% 
  select(Time,Swimmer,Date,Location) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "400", Stroke = "Free", Format = "sc", Sex = "M")
men_400free_sc$Swimmer <- name_fun(men_400free_sc$Swimmer)
men_400free_sc$Date <- as.Date(men_400free_sc$Date, format = "%d %b %Y")
men_400free_sc$Time <- time_fun(men_400free_sc$Time)

women_400free_lc <- html_table(tables_400free[[3]], fill = TRUE) %>% 
  select(Time = TIME,Swimmer = SWIMMER,Date = DATE, Location = PLACE) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "400", Stroke = "Free", Format = "lc", Sex = "W")
women_400free_lc$Swimmer <- name_fun(women_400free_lc$Swimmer)
women_400free_lc$Date <- as.Date(women_400free_lc$Date, format = "%d %b %Y")
women_400free_lc$Time <- time_fun(women_400free_lc$Time)

women_400free_sc <- html_table(tables_400free[[4]]) %>% 
  select(Time = TIME,Swimmer = SWIMMER, Date = DATE, Location = PLACE) %>% 
  mutate(Time = str_sub(Time, 1, nchar(Time)/2)) %>%
  mutate(Distance = "400", Stroke = "Free", Format = "sc", Sex = "W")
women_400free_sc$Swimmer <- name_fun(women_400free_sc$Swimmer)
women_400free_sc$Date <- as.Date(women_400free_sc$Date, format = "%d %b %Y")
women_400free_sc$Time <- time_fun(women_400free_sc$Time)
women_400free_sc$Time[11] <- 233.92
women_400free_sc$Swimmer[11] <- "Ariarne Titmus"
women_400free_sc$Time[4] <- 239.53 #Fixing some small issues by manually inputting certain values. 
women_400free_sc$Time[5] <- 236.79
women_400free_sc$Time[6] <- 234.92
women_400free_sc$Time[7] <- 233.92
women_400free_sc <- women_400free_sc %>% slice(-1) # The oldest entry in the table had all major variables missing so this case was removed. 
```

```{r, 400 Free Nationality Adjustments}

#Manually entering nationality given that the entries were represented by a flag in the original dataset.

men_400free_lc$Nationality <- c("Great Britain", "Great Britain", "Hungary", "Hungary", "Canada", "Great Britain", "United States", "United States", "Sweden", "United States", "United States", "Sweden", "Sweden", "France", "Japan", "United States", "United States", "France", "Japan", "Japan", "Australia", "Australia", "Australia", "United States", "Australia", "Australia", "Australia", "Australia", "Australia", "Japan", "Australia", "Australia", "United States", "United States", "United States", "United States", "East Germany", "United States", "France", "United States", "United States", "United States", "Canada", "Germany", "United States", "Sweden", "United States", "Australia", "United States", "United States", "United States", "United States","United States","United States","United States","United States","United States", "Soviet Union", "Soviet Union", "Soviet Union", "Canada", "Soviet Union", "Soviet Union", "Soviet Union", "Germany", "Poland", "East Germany", "Australia", "Unattached", "Australia", "Australia", "Australia", "Australia", "Australia","Australia", "Germany")

men_400free_sc$Nationality <- c("Italy", "Sweden", "Australia", "Australia", "Australia", "Australia", "Germany", "France")

women_400free_lc$Nationality <- c("United States", "Great Britain", "United States" , "United States" , "United States","United States", "United States", "United States" , "United States" , "Netherlands", "Denmark", "Denmark", "Denmark", "Denmark", "Denmark", "Denmark", "Denmark", "Denmark", "Australia", "Australia", "Australia","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","United States","Australia","Australia", "Australia","United States","United States","United States","United States","East Germany", "East Germany", "East Germany","United States", "Australia", "United States", "United States", "France", "France", "Italy", "Great Britain", "Italy", "Italy", "United States", "United States", "United States")

women_400free_sc$Nationality <- c("East Germany", "Costa Rica", "United States",  "France", "France", "Great Britain", "France", "Spain", "China", "Australia")

free400 <- bind_rows(men_400free_lc,men_400free_sc,women_400free_lc, women_400free_sc)  #Binding data into cumulative dataframe. 
```


```{r, 800 Free}

#Reading in URL for 800 free. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 

url_800free <- "https://en.wikipedia.org/wiki/World_record_progression_800_metres_freestyle"

page_800free <- read_html(url_800free)

tables_800free <- html_nodes(page_800free, "table")

men_800free_lc <- html_table(tables_800free[[1]]) %>%
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "800", Stroke = "Free", Format = "lc", Sex = "M")
men_800free_lc$Date <- as.Date(men_800free_lc$Date, format = "%b %d, %Y")
men_800free_lc$Time <- time_fun(men_800free_lc$Time)

men_800free_sc <- html_table(tables_800free[[2]]) %>%
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "800", Stroke = "Free", Format = "sc", Sex = "M")
men_800free_sc$Date <- as.Date(men_800free_sc$Date, format = "%b %d, %Y")
men_800free_sc$Time <- time_fun(men_800free_sc$Time)

women_800free_lc <- html_table(tables_800free[[3]]) %>%
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "800", Stroke = "Free", Format = "lc", Sex = "W")
women_800free_lc$Date <- as.Date(parse_date_time(women_800free_lc$Date,  c("%d %B %Y", "%b %d, %Y")))
women_800free_lc$Time <- time_fun(women_800free_lc$Time)

women_800free_sc <- html_table(tables_800free[[4]]) %>%
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "800", Stroke = "Free", Format = "sc", Sex = "W")
women_800free_sc$Date <- as.Date(women_800free_sc$Date, format = "%b %d, %Y")
women_800free_sc$Time <- time_fun(women_800free_sc$Time)

free800 <- bind_rows(men_800free_lc, men_800free_sc, women_800free_lc, women_800free_sc)  #Binding data into cumulative dataframe. 
```



```{r, 1500 Free}

#Reading in URL for 1500 free. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 

url_1500free <- "https://en.wikipedia.org/wiki/World_record_progression_1500_metres_freestyle"

page_1500free <- read_html(url_1500free) 

tables_1500free <- html_nodes(page_1500free, "table")

men_1500free_lc <- html_table(tables_1500free[[1]]) %>% 
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "1500", Stroke = "Free", Format = "lc", Sex = "M")
men_1500free_lc$Date <- as.Date(men_1500free_lc$Date, format = "%b %d, %Y")
men_1500free_lc$Time <- time_fun(men_1500free_lc$Time)

men_1500free_sc <- html_table(tables_1500free[[2]]) %>%
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "1500", Stroke = "Free", Format = "sc", Sex = "M")
men_1500free_sc$Date <- as.Date(men_1500free_sc$Date, format = "%b %d, %Y")
men_1500free_sc$Time <- time_fun(men_1500free_sc$Time)

women_1500free_lc <- html_table(tables_1500free[[3]]) %>%
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "1500", Stroke = "Free", Format = "lc", Sex = "W")
women_1500free_lc$Date <- as.Date(women_1500free_lc$Date, format = "%b %d, %Y")
women_1500free_lc$Time <- time_fun(women_1500free_lc$Time)

women_1500free_sc <- html_table(tables_1500free[[4]]) %>%
  select(Time,Swimmer = Name,Date,Nationality,Location) %>%
  mutate(Distance = "1500", Stroke = "Free", Format = "sc", Sex = "W")
women_1500free_sc$Date <- as.Date(women_1500free_sc$Date, format = "%b %d, %Y")
women_1500free_sc$Time <- time_fun(women_1500free_sc$Time)

free1500 <- bind_rows(men_1500free_lc,men_1500free_sc,women_1500free_lc,women_1500free_sc) #Binding data into cumulative data frame. 
```


```{r, Binding Freestyle}

free <- bind_rows(free50,free100,free200,free400,free800,free1500)  #Binding data into cumulative dataframe. At this stage in the binding there exists a table for all the freestyle events. 
```
 
```{r, 100 Back}

#Reading in URL for 100 back. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 

url_100back <- "https://en.wikipedia.org/wiki/World_record_progression_100_metres_backstroke"

page_100back <- read_html(url_100back)

tables_100back <- html_nodes(page_100back, "table")

men_100back_lc <- html_table(tables_100back[[1]]) %>%
  select(Time, Swimmer, Date, Location = Place) %>%
  mutate(Distance = "100", Stroke = "Back", Format = "lc", Sex = "M")
men_100back_lc$Date <- as.Date(men_100back_lc$Date, format = "%B %d, %Y")
men_100back_lc$Time <- str_replace_all(men_100back_lc$Time, "[(r)]", "")
men_100back_lc$Time <- time_fun(men_100back_lc$Time)

men_100back_sc <- html_table(tables_100back[[2]]) %>%
  select(Time, Swimmer = `Swimmer[1]`, Date, Location = Place) %>%
  mutate(Distance = "100", Stroke = "Back", Format = "sc", Sex = "M")
men_100back_sc$Date <- as.Date(men_100back_sc$Date, format = "%B %d, %Y")
men_100back_sc$Time[1] <- "52.71" 
men_100back_sc$Time[2] <- "52.58"
men_100back_sc$Time[3] <- "52.52" #Fixing some small issues by manually inputting certain values. 
men_100back_sc$Time[17] <- "48.94"
men_100back_sc$Time[18] <- "48.92"
men_100back_sc$Time[19] <- "48.90"
men_100back_sc$Time[20] <- "48.88"
men_100back_sc$Time <- time_fun(men_100back_sc$Time)

women_100back_lc <- html_table(tables_100back[[3]]) %>%
  select(Time, Swimmer, Date, Location = Place) %>%
  mutate(Distance = "100", Stroke = "Back", Format = "lc", Sex = "W")
women_100back_lc$Date <- as.Date(women_100back_lc$Date, format = "%B %d, %Y")
women_100back_lc$Time <- str_replace_all(women_100back_lc$Time, "[(re)]", "")
women_100back_lc$Time <- time_fun(women_100back_lc$Time)

women_100back_sc <- html_table(tables_100back[[4]]) %>%
  select(Time, Swimmer= `Swimmer[8]`, Date, Location = Place) %>%
  mutate(Distance = "100", Stroke = "Back", Format = "sc", Sex = "W")
women_100back_sc$Date <- as.Date(women_100back_sc$Date, format = "%B %d, %Y")
women_100back_sc$Time <- time_fun(women_100back_sc$Time)
```

```{r, 100 Back}

#Manually entering nationality given that the entries were represented by a flag in the original dataset. 

men_100back_lc$Nationality <- c("Australia", "Australia", "United States", "United States", "United States", "Germany", "United States", "United States", "United States", "United States", "United States", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "United States","United States","United States","United States","United States","Soviet Union", "Soviet Union", "Soviet Union", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "Spain", "United States", "United States")

men_100back_sc$Nationality <- c("Canada", "Canada", "Canada", "Canada", "United States", "United States", "United States", "Germany", "United States", "United States", "United States", "United States", "Russia", "Spain", "Russia", "Russia", "United States", "United States", "Russia", "China")

women_100back_lc$Nationality <- c("United States", "South Africa", "Canada", "Canada", "South Africa", "South Africa", "United States", "South Africa", "East Germany", "East Germany", "Canada", "East Germany","East Germany","East Germany","East Germany","East Germany","East Germany","East Germany","East Germany","East Germany","East Germany","East Germany", "Hungary", "China", "United States", "United States", "United States", "United States", "United States", "United States", "Zimbabwe", "Russia", "Great Britain", "Canada", "United States", "United States")

women_100back_sc$Nationality <- c("United States", "United States", "Japan", "United States", "United States", "United States", "Japan", "Japan", "Hungary", "Australia") 

back100 <- bind_rows(men_100back_lc,men_100back_sc,women_100back_lc,women_100back_sc) #Binding data into cumulative dataframe. 
```



```{r, 200 Back}

#Reading in URL for 200 back. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 
url_200back <- "https://en.wikipedia.org/wiki/World_record_progression_200_metres_backstroke"

page_200back <- read_html(url_200back) 

tables_200back <- html_nodes(page_200back, "table")

men_200back_lc <- html_table(tables_200back[[2]]) %>% 
  select(Time, Swimmer = Name, Nationality, Date, Location) %>%
  mutate(Distance = "200", Stroke = "Back", Format = "lc", Sex = "M")
men_200back_lc$Date <- as.Date(men_200back_lc$Date, "%d %B %Y")
men_200back_lc$Time <- time_fun(men_200back_lc$Time)

men_200back_sc <- html_table(tables_200back[[3]]) %>% 
  select(Time, Swimmer = Name, Nationality, Date, Location) %>%
  mutate(Distance = "200", Stroke = "Back", Format = "lc", Sex = "M")
men_200back_sc$Date <- as.Date(men_200back_sc$Date, "%d %B %Y")
men_200back_sc$Time <- time_fun(men_200back_sc$Time)

women_200back_lc <- html_table(tables_200back[[5]]) %>% 
  select(Time, Swimmer = Name, Nationality, Date, Location) %>%
  mutate(Distance = "200", Stroke = "Back", Format = "lc", Sex = "W")
women_200back_lc$Date <- as.Date(women_200back_lc$Date, "%d %b %Y")
women_200back_lc$Time <- time_fun(women_200back_lc$Time)

women_200back_sc <- html_table(tables_200back[[6]]) %>% 
  select(Time, Swimmer = Name, Nationality, Date, Location) %>%
  mutate(Distance = "200", Stroke = "Back", Format = "sc", Sex = "W")
women_200back_sc <- women_100back_sc %>% slice(-1)
women_200back_sc$Date <- as.Date(women_200back_sc$Date, tryFormats = c("%d %b %Y", "%d %B %Y"))
women_200back_sc$Time <- time_fun(women_200back_sc$Time)

back200 <- bind_rows(men_200back_lc,men_200back_sc,women_200back_lc,women_200back_sc)
back <- bind_rows(back100,back200)  #Binding data into cumulative data frame. At this stage in the binding of the there exists a dataframe with all of the backstroke events. 

```


```{r, 200 Back Nationality Adjustments}

#Reading in URL for 100 breast. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable. 
url_100breast <- "https://en.wikipedia.org/wiki/World_record_progression_100_metres_breaststroke"

page_100breast <- read_html(url_100breast)

tables_100breast <- html_nodes(page_100breast, "table")

men_100breast_lc <- html_table(tables_100breast[[1]]) %>%
  mutate(Distance = "100", Stroke = "Breast", Format = "lc", Sex = "M")
men_100breast_lc <- men_100breast_lc %>% rename(Swimmer = Name)
men_100breast_lc$Date <- as.Date(men_100breast_lc$Date, tryFormats = c("%B %d, %Y", "%b %d, %Y", "%d %B %Y"))
men_100breast_lc$Time <- time_fun(men_100breast_lc$Time)

men_100breast_sc <- html_table(tables_100breast[[2]]) %>%
  mutate(Distance = "100", Stroke = "Breast", Format = "sc", Sex = "M")
men_100breast_sc <- men_100breast_sc %>% rename(Swimmer = Name)
men_100breast_sc$Date <- as.Date(parse_date_time(men_100breast_sc$Date, c("%B %d, %Y", "%b %d, %Y", "%d %B %Y")))
men_100breast_sc$Time <- time_fun(men_100breast_sc$Time)

women_100breast_lc <- html_table(tables_100breast[[3]]) %>%
  mutate(Distance = "100", Stroke = "Breast", Format = "lc", Sex = "W")
women_100breast_lc <- women_100breast_lc %>% rename(Swimmer = Name)
women_100breast_lc$Date <- as.Date(women_100breast_lc$Date, tryFormats = c("%B %d, %Y", "%b %d, %Y", "%d %B %Y"))
women_100breast_lc$Time <- time_fun(women_100breast_lc$Time)

women_100breast_sc <- html_table(tables_100breast[[4]]) %>%
  mutate(Distance = "100", Stroke = "Breast", Format = "sc", Sex = "W")
women_100breast_sc <- women_100breast_sc %>% rename(Swimmer = Name)
women_100breast_sc$Date <- as.Date(women_100breast_sc$Date, tryFormats = c("%B %d, %Y", "%b %d, %Y", "%d %B %Y"))

women_100breast_sc$Time[1] <- "1:06.58"
women_100breast_sc$Time[2] <- "1:05.70"
women_100breast_sc$Time[14] <- "1:02.36"
women_100breast_sc$Time[15] <- "1:02.36"
women_100breast_sc$Time <- time_fun(women_100breast_sc$Time)
breast100 <- bind_rows(men_100breast_lc,men_100breast_sc,women_100breast_lc,women_100breast_sc)  #Binding data into cumulative dataframe. 
```



```{r, Time Formatting Function-Breastroke}

#Creating a function to clean the formatting of all the breatstroke events. 

breast_time <- function(x){
  times <- x
  for (i in 1:length(times)){
    times[i] <- str_split(times[i], " ")[[1]][1]
  }
  return(time)
}
```

```{r, 200 Breast}

#Reading in URL for 200 breast. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable.

url_200breast <- "https://en.wikipedia.org/wiki/World_record_progression_200_metres_breaststroke"

page_200breast <- read_html(url_200breast)

tables_200breast <- html_nodes(page_200breast, "table")

men_200breast_lc <- html_table(tables_200breast[[1]]) %>%
  mutate(Distance = "200", Stroke = "Breast", Format = "lc", Sex = "M")
men_200breast_lc <- men_200breast_lc %>% rename(Location = Place) 
men_200breast_lc$Date <- as.Date(men_200breast_lc$Date, format = "%B %d, %Y")
men_200breast_lc$Time <- str_replace_all(men_200breast_lc$Time, "\\[|\\]|e", ":")
men_200breast_lc$Time <- breast_time(men_200breast_lc$Time)
men_200breast_lc$Time <- time_fun(men_200breast_lc$Time)

men_200breast_sc <- html_table(tables_200breast[[2]]) %>%
  mutate(Distance = "200", Stroke = "Breast", Format = "sc", Sex = "M")
men_200breast_sc <- men_200breast_sc %>% rename(Location = Place)
men_200breast_sc$Date <- as.Date(men_200breast_sc$Date, format = "%B %d, %Y")
men_200breast_sc$Time <- str_replace_all(men_200breast_sc$Time, "\\[|\\]", " ")
men_200breast_sc$Time <- breast_time(men_200breast_sc$Time)
men_200breast_sc$Time <- time_fun(men_200breast_sc$Time)

women_200breast_lc <- html_table(tables_200breast[[3]]) %>%
  mutate(Distance = "200", Stroke = "Breast", Format = "lc", Sex = "W")
women_200breast_lc <- women_200breast_lc %>% rename(Location = Place)
women_200breast_lc$Date <- as.Date(women_200breast_lc$Date, format = "%B %d, %Y")
women_200breast_lc$Time <- str_replace_all(women_200breast_lc$Time, "=|e", " ")
women_200breast_lc$Time <- breast_time(women_200breast_lc$Time)
women_200breast_lc$Time <- time_fun(women_200breast_lc$Time)

women_200breast_sc <- html_table(tables_200breast[[4]]) %>%
  mutate(Distance = "200", Stroke = "Breast", Format = "sc", Sex = "W")
women_200breast_sc <- women_200breast_sc %>% rename(Location = Place)
women_200breast_sc$Date <- as.Date(women_200breast_sc$Date, format = "%B %d, %Y")
women_200breast_sc$Time <- str_replace_all(women_200breast_sc$Time, "\\[|\\]", " ")
women_200breast_sc$Time <- breast_time(women_200breast_sc$Time)
women_200breast_sc$Time <- time_fun(women_200breast_sc$Time)

```

```{r, 200 Breast Nationality Adjustments}

#Manually entering nationality given that the entries were represented by a flag in the original dataset. 

men_200breast_lc$Nationality <- c("Great Britain", "Sweden", "Belgium", "Great Britain", "Germany", "United States", "Germany", "Germany", "Japan", "United States", "United States", "France", "Germany",  "France", "United States", "France", "United States", "United States", "United States", "Germany",  "Australia", "United States", "United States", "United States", "United States", "Germany", "Denmark", "Japan", "Japan", "Japan", "Japan", "Japan", "Australia", "United States", "United States", "United States", "Australia", "China", "China", "China", "United States", "United States", "United States", "United States", "Great Britain", "United States", "United States", "Great Britain", "Canada", "Canada", "Canada", "United States", "Great Britain", "United States", "United States", "United States", "United States", "United States", "Japan", "Russia", "Japan", "United States", "United States", "United States", "Japan", "Australia", "Hungary", "Japan", "Japan", "Australia", "Russia")
men_200breast_sc$Nationality <- c("Great Britain", "Australia", "Russia", "Russia", "United States", "United States", "United States", "United States", "United States", "Australia", "Hungary", "Hungary", "Germany", "Russia")

women_200breast_lc$Nationality <- c("Belgium", "Belgium", "Belgium", "Great Britain", "Germany", "Sweden", "Netherlands", "Denmark", "Germany", "Netherlands","Germany", "Great Britain", "Australia", "Germany", "Denmark", "Japan", "Netherlands", "Netherlands", "Netherlands", "Brazil", "Germany", "Netherlands", "Netherlands", "Netherlands", "Hungary", "Hungary", "Netherlands", "Netherlands", "Netherlands", "Netherlands", "Great Britain", "Germany", "Great Britain", "East Germany", "Soviet Union", "Soviet Union", "Soviet Union", "Soviet Union", "United States", "United States", "United States", "East Germany", "East Germany", "East Germany", "Soviet Union", "Soviet Union", "Soviet Union", "Soviet Union", "Soviet Union", "Soviet Union", "East Germany", "East Germany", "East Germany", "Canada", "East Germany", "United States", "United States", "Australia", "South Africa", "South Africa", "South Africa", "South Africa", "China", "United States", "Australia", "United States", "Australia", "Australia", "United States", "Canada", "United States", "United States", "Denmark")

women_200breast_sc$Nationality <- c("East Germany", "China", "China", "Australia", "Japan", "China", "China", "Australia", "Canada", "Canada", "Australia", "United States", "Russia")

breast200 <- bind_rows(men_200breast_lc,men_200breast_sc,women_200breast_lc,women_200breast_sc)
breast <- bind_rows(breast100,breast200) #Binding data into cumulative dataframe. At this stage in the binding there exists a table for all the breaststroke events. 
```


```{r, 100 Fly}

#Reading in URL for 100 fly. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable.

url_100fly <- "https://en.wikipedia.org/wiki/World_record_progression_100_metres_butterfly"

page_100fly <- read_html(url_100fly)

tables_100fly <- html_nodes(page_100fly, "table")

men_100fly_lc <- html_table(tables_100fly[[1]]) %>%
  select(Time, Swimmer, Date, Location = Place) %>%
  mutate(Distance = "100", Stroke = "Fly", Format = "lc", Sex = "M")
men_100fly_lc$Date <- as.Date(men_100fly_lc$Date, format = "%B %d, %Y")
men_100fly_lc$Time <- time_fun(men_100fly_lc$Time)

men_100fly_sc <- html_table(tables_100fly[[2]]) %>%
  select(Time, Swimmer, Date,Location = Place) %>%
  mutate(Distance = "100", Stroke = "Fly", Format = "sc", Sex = "M")
men_100fly_sc$Date <- as.Date(men_100fly_sc$Date, format = "%B %d, %Y")
men_100fly_sc$Time <- str_replace_all(men_100fly_sc$Time, "\\[|\\]", " ")
men_100fly_sc$Time <- breast_time(men_100fly_sc$Time)
men_100fly_sc$Time <- time_fun(men_100fly_sc$Time)
men_100fly_sc[]

women_100fly_lc <- html_table(tables_100fly[[3]]) %>%
  select(Time, Swimmer, Date,Location = Place) %>%
  mutate(Distance = "100", Stroke = "Fly", Format = "lc", Sex = "W")
women_100fly_lc$Date <- as.Date(women_100fly_lc$Date, format = "%B %d, %Y")
women_100fly_lc$Time <- time_fun(women_100fly_lc$Time)

women_100fly_sc <- html_table(tables_100fly[[4]]) %>%
  select(Time, Swimmer, Date,Location = Place) %>%
  mutate(Distance = "100", Stroke = "Fly", Format = "sc", Sex = "W")
women_100fly_sc$Date <- as.Date(women_100fly_sc$Date, format = "%B %d, %Y")
women_100fly_sc$Time <- time_fun(women_100fly_sc$Time)
```

```{r, 100 Fly Nationality Adjustments}

#Manually entering nationality given that the entries were represented by a flag in the original dataset. 

men_100fly_lc$Nationality <- c("Hungary", "Japan", "Japan", "Japan", "Japan", "Japan", "United States", "United States", "United States", "Argentina", "Argentina", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "Sweden", "United States", "United States", "United States", "Germany", "United States", "Russia", "Russia", "Australia", "Australia", "Australia", "Ukraine", "United States", "United States", "United States", "United States", "United States", "Serbia", "United States", "United States")

men_100fly_sc$Nationality <- c("Canada", "Russia", "Russia", "Russia", "Australia", "Australia", "Great Britain", "Australia", "Sweden", "Sweden", "Germany", "Germany", "Serbia and Montenegro", "United States", "United States", "Russia", "Russia", "South Africa", "South Africa")

women_100fly_lc$Nationality <- c("Netherlands", "United States", "United States", "Australia", "Canada", "United States", "Canada", "United States", "Netherlands", "Netherlands", "United States", "Netherlands", "United States", "Japan", "Hungary", "Japan", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "United States", "United States", "United States", "Netherlands", "Netherlands", "Netherlands", "Sweden", "Sweden", "United States", "Sweden", "Sweden", "Sweden")

women_100fly_sc$Nationality <- c("Australia", "China", "United States", "Japan", "United States", "United States", "United States", "United States", "Slovakia", "United States", "Australia", "Australia", "Australia", "Australia", "Australia", "France", "Sweden")

fly100 <- bind_rows(men_100fly_lc,men_100fly_sc, women_100fly_lc, women_100fly_sc) #Binding data into cumulative dataframe. 
```

```{r, 200 Fly}

#Reading in URL for 200 fly. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable.

url_200fly <- "https://en.wikipedia.org/wiki/World_record_progression_200_metres_butterfly"

page_200fly <- read_html(url_200fly)

tables_200fly <- html_nodes(page_200fly, "table")

men_200fly_lc <- html_table(tables_200fly[[1]]) %>%
  rename(Location = Place) %>%
  mutate(Distance = "200", Stroke = "Fly", Format = "lc", Sex = "M")
men_200fly_lc$Date <- as.Date(men_200fly_lc$Date, format = "%B %d, %Y")
men_200fly_lc$Time <- time_fun(men_200fly_lc$Time)

men_200fly_sc <- html_table(tables_200fly[[2]]) %>%
  rename(Location = Place) %>%
  mutate(Distance = "200", Stroke = "Fly", Format = "sc", Sex = "M")
men_200fly_sc$Date <- as.Date(men_200fly_sc$Date, format = "%B %d, %Y")
men_200fly_sc$Time <- time_fun(men_200fly_sc$Time)

women_200fly_lc <- html_table(tables_200fly[[3]]) %>%
  rename(Location = Place) %>%
  mutate(Distance = "200", Stroke = "Fly", Format = "lc", Sex = "W")
women_200fly_lc$Date <- as.Date(women_200fly_lc$Date, format = "%B %d, %Y")
women_200fly_lc$Time[29] <- "2:09.87"
women_200fly_lc$Time <- time_fun(women_200fly_lc$Time)

women_200fly_sc <- html_table(tables_200fly[[4]]) %>%
  rename(Location = Place) %>%
  mutate(Distance = "200", Stroke = "Fly", Format = "sc", Sex = "W")
women_200fly_sc$Date <- as.Date(women_200fly_sc$Date, format = "%B %d, %Y")
women_200fly_sc$Time <- time_fun(women_200fly_sc$Time)
```

```{r, 200 Fly Nationality Adjustments}

#Manually entering nationality given that the entries were represented by a flag in the original dataset. 

men_200fly_lc$Nationality <- c("United States", "United States", "United States", "United States", "United States", "United States", "United States", "Australia" , "United States", "United States", "Australia" , "Australia" , "United States", "Australia" , "Australia" , "United States", "United States", "United States", "United States", "United States", "United States", "Germany", "United States", "United States", "United States", "East Germany", "East Germany", "United States", "United States", "United States", "East Germany", "Australia" , "Germany", "Germany", "Germany", "United States", "Russia", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "Hungary")

men_200fly_sc$Nationality <- c("France", "Australia" , "Australia" , "Australia" , "France", "Russia", "Great Britain", "France", "Germany", "France", "Russia", "Russia", "Brazil", "South Africa", "South Africa", "Japan")

women_200fly_lc$Nationality <- c("United States", "Netherlands", "United States", "Netherlands", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "Netherlands", "Netherlands", "Netherlands", "Netherlands", "United States", "United States", "United States", "United States", "United States", "United States", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "United States", "United States", "United States", "United States", "United States", "United States", "Australia" , "Poland", "Poland", "Australia" , "China", "United States", "Australia" , "China")

women_200fly_sc$Nationality <- c("Australia" , "Australia", "Australia", "China", "Poland", "Japan", "China", "China", "Spain")

fly200 <- bind_rows(men_200fly_lc,men_200fly_sc,women_200fly_lc,women_200fly_sc)
fly <- bind_rows(fly100,fly200) #Binding data into cumulative dataframe. At this stage in the binding there exists a table for all the fly events. 
```

```{r, 200 IM}

#Reading in URL for 200 IM. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable.

url_200im <- "https://en.wikipedia.org/wiki/World_record_progression_200_metres_individual_medley"

page_200im <- read_html(url_200im)

tables_200im <- html_nodes(page_200im, "table")

men_200im_lc <- html_table(tables_200im[[1]], fill = TRUE) %>%
  select(Time = TIME, Swimmer = SWIMMER, Nationality = NATIONALITY, Date = DATE, Location = PLACE) %>%
  mutate(Distance = "200", Stroke = "IM", Format = "lc", Sex = "M")
men_200im_lc$Date <- as.Date(men_200im_lc$Date, format = "%B %d, %Y")
men_200im_lc$Time[23] <- "2:06.32"
men_200im_lc$Time <- time_fun(men_200im_lc$Time)

men_200im_sc <- html_table(tables_200im[[2]], fill = TRUE) %>%
  select(Time = TIME, Swimmer = SWIMMER, Nationality = NATIONALITY, Date = DATE, Location = PLACE) %>%
  mutate(Distance = "200", Stroke = "IM", Format = "sc", Sex = "M")
men_200im_sc$Date <- as.Date(men_200im_sc$Date, format = "%B %d, %Y")
men_200im_sc$Time[6] <- "1:54.65"
men_200im_sc$Time <- time_fun(men_200im_sc$Time)

women_200im_lc <- html_table(tables_200im[[3]]) %>%
  select(Time = TIME, Swimmer = SWIMMER, Nationality = NATIONALITY, Date = DATE, Location = PLACE) %>%
  mutate(Distance = "200", Stroke = "IM", Format = "lc", Sex = "W")
women_200im_lc$Date <- as.Date(women_200im_lc$Date, format = "%B %d, %Y")
women_200im_lc$Time <- time_fun(women_200im_lc$Time)

women_200im_sc <- html_table(tables_200im[[4]]) %>%
  select(Time = TIME, Swimmer = SWIMMER, Nationality = NATIONALITY, Date = DATE, Location = PLACE) %>%
  mutate(Distance = "200", Stroke = "IM", Format = "sc", Sex = "W")
women_200im_sc$Date <- as.Date(women_200im_sc$Date, format = "%B %d, %Y")
women_200im_sc$Time <- time_fun(women_200im_sc$Time)

im200 <- bind_rows(men_200im_lc,men_200im_sc, women_200im_lc, women_200im_sc) #Binding data into cumulative dataframe. 
```


```{r, 400 IM}

#Reading in URL for 400 IM. Pulling tables for long course and short course for both men and women. Adjusting some formatting in the table. Adjustments made to date variable and applying the time adjustment function to time variable.


url_400im <- "https://en.wikipedia.org/wiki/World_record_progression_400_metres_individual_medley"

page_400im <- read_html(url_400im)

tables_400im <- html_nodes(page_400im, "table")

men_400im_lc <- html_table(tables_400im[[1]], fill = TRUE) %>%
  rename(Location = Place) %>%
  mutate(Distance = "400", Stroke = "IM", Format = "lc", Sex = "M")
men_400im_lc$Date <- as.Date(men_400im_lc$Date, format = "%d %B %Y")
men_400im_lc$Time[46] <- "4:03.84"
men_400im_lc$Time <- time_fun(men_400im_lc$Time)

men_400im_sc <- html_table(tables_400im[[2]], fill = TRUE) %>%
  mutate(Distance = "400", Stroke = "IM", Format = "sc", Sex = "M")
men_400im_sc$Date <- as.Date(men_400im_sc$Date, format = "%d %B %Y")
men_400im_sc$Time <- time_fun(men_400im_sc$Time)

women_400im_lc <- html_table(tables_400im[[3]]) %>%
  rename(Location = Place) %>%
  mutate(Distance = "400", Stroke = "IM", Format = "lc", Sex = "W")
women_400im_lc$Date <- as.Date(women_400im_lc$Date, format = "%d %B %Y")
women_400im_lc$Time <- time_fun(women_400im_lc$Time)

women_400im_sc <- html_table(tables_400im[[4]]) %>%
  select(Time,Swimmer = Name, Nationality,Date,Location) %>%
  mutate(Distance = "400", Stroke = "IM", Format = "lc", Sex = "W")
women_400im_sc$Date <- as.Date(women_400im_sc$Date, format = "%d %B %Y")
women_400im_sc$Time <- time_fun(women_400im_sc$Time)
```

```{r, 400 IM Nationality Adjustments}

#Manually entering nationality given that the entries were represented by a flag in the original dataset.

men_400im_lc$Nationality <- c("United States", "Soviet Union", "Great Britain", "United States", "United States", "United States", "United States", "United States", "Germany", "United States", "United States", "Germany", "United States", "United States", "Soviet Union", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "Hungary", "Hungary", "United States", "United States", "United States", "Brazil", "East Germany", "Canada", "Canada", "United States", "Hungary", "Hungary", "Hungary", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States")

women_400im_lc$Nationality <- c("United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "Australia", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "East Germany", "United States", "East Germany", "East Germany", "East Germany", "East Germany", "China", "Ukraine", "United States", "Australia", "United States", "Australia", "China", "Hungary")

im400 <- bind_rows(men_400im_lc,men_400im_sc, women_400im_lc, women_400im_sc)
im <- bind_rows(im200,im400) #Binding data into cumulative dataframe. At this stage in the binding there exists a table for all the IM events. 
```

```{r, Binding Cumulative Dataframe}
record_data <- bind_rows(free,back,breast,fly,im) 
record_data$Time[1291] <- 52.07 #Fixing some small issues by manually inputting certain values. 
record_data$Time[1292] <- 51.94
record_data$Time[1163] <- 120.44
record_data$Time[1250] <- 134.39

#Binding data into cumulative dataframe. At this stage in the binding there exists a table with all the events, thus the table is complte.

```


```{r}
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "ó", "o")
record_data$Location <- str_replace_all(record_data$Location, "ó", "o")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "ö", "o")
record_data$Location <- str_replace_all(record_data$Location, "ö", "o")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "z", "z")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "é", "e")
record_data$Location <- str_replace_all(record_data$Location, "é", "e")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "è", "e")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "á", "a")
record_data$Location <- str_replace_all(record_data$Location, "á", "a")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "ä", "a")
record_data$Location <- str_replace_all(record_data$Location, "ã", "a")
record_data$Location <- str_replace_all(record_data$Location, "ä", "a")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "ü", "u")
record_data$Location <- str_replace_all(record_data$Location, "ü", "u")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "ú", "u")
record_data$Swimmer <- str_replace_all(record_data$Swimmer, "ø", "o")
```

```{r}
record_data <- record_data %>% mutate(Event = paste(Distance, " ", Stroke))
```


```{r}
write.csv(record_data, "math285finaldata.csv")
```

